baseURL = "https://everydayna.art/"
languageCode = "en-us"
title = "everyday.na"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "everydayna"
googleAnalytics = "UA-118294122-3"
enableGitInfo = true
theme = ["beautifulhugo"]
enableEmoji=true

[Params]
  homeTitle = "everyday.na" # Set a different text for the header on the home page
  subtitle = "Welcome to Nicole, and Anthony's side of the world."
  mainSections = ["post","posts","recipe"]
  logo = "root/n-and-a.jpg" # Expecting square dimensions
  favicon = "root/8-bit-heart.png"
  dateFormat = "January 2, 2006"
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  commit = "https://github.com/rabbito-home/everyday-na/tree/"
  hideAuthor = false
  gcse = "bb80d66b27f3857eb" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Anthony & Nicole"
  website = "everydayna.art"
  email = "nicolmartinezm99@gmail.com"
  facebook = "nikiibebemartinez"
  github = "rabbito-home"
  #gitlab = "username"
  #bitbucket = "username"
  twitter = "wow_itsnikky"
  reddit = "NickyMart"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  instagram = "everyday.na"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = ""
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Blog"
    url = "post"
    weight = 1

[[menu.main]]
    name = "Recipes"
    url = "recipe"
    weight = 2

[[menu.main]]
    name = "About Us"
    url = "page/about/"
    weight = 4

[[menu.main]]
    identifier = "links"
    name = "Links"
    weight = 3

[[menu.main]]
    parent = "links"
    name = "Anthony"
    url = "https://www.instagram.com/anthonyrabbito/"
    weight = 1

[[menu.main]]
    parent = "links"
    name = "Nicole"
    url = "https://www.instagram.com/wow_itsnikky/"
    weight = 2

[[menu.main]]
    parent = "links"
    name = "MyFitnessPal"
    url = "https://www.myfitnesspal.com/"
    weight = 3

[[menu.main]]
    parent = "links"
    name = "Zero App"
    url = "https://www.zerofasting.com/"
    weight = 4

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[languages]
  [languages.en] 
    contentDir = "content/en" # English
  [languages.es]
    contentDir = "content/es" # Spanish
